services:
  # Frontend Service (Vue.js served by Nginx)
  frontend-service:
    build:
      context: ./frontend-service
    ports:
      - "8090:80" # Expose on port 8090 to avoid conflict
    depends_on:
      - gateway-service

  # Gateway Service (Node.js)
  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    command: npm run dev
    depends_on:
      - user-service
      - chatbot-service

  # User Service (Laravel/PHP)
  user-service:
    build:
      context: ./user-service
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - ./user-service:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Chatbot Service (Python/Flask)
  chatbot-service:
    build:
      context: ./chatbot-service
    ports:
      - "5001:5001"
    env_file:
      - .env.docker
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5001

  # Monitoring (Optional)
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000" # Use 3001 to avoid conflict with gateway

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
